[dependencies]
reqwest = { version = "0.11", features = ["json"] }
rodio = "0.14"
tempfile = "3.7"
uuid = { version = "1", features = ["v4"] }
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.17"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
